/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PRS01 = 8;
  /** RegularExpression Id. */
  int PRS02 = 9;
  /** RegularExpression Id. */
  int PRS03 = 10;
  /** RegularExpression Id. */
  int PRS04 = 11;
  /** RegularExpression Id. */
  int PRS05 = 12;
  /** RegularExpression Id. */
  int PRS06 = 13;
  /** RegularExpression Id. */
  int PRS07 = 14;
  /** RegularExpression Id. */
  int PRS08 = 15;
  /** RegularExpression Id. */
  int PRS09 = 16;
  /** RegularExpression Id. */
  int PRS10 = 17;
  /** RegularExpression Id. */
  int PRS11 = 18;
  /** RegularExpression Id. */
  int PRS12 = 19;
  /** RegularExpression Id. */
  int PRS13 = 20;
  /** RegularExpression Id. */
  int PRS14 = 21;
  /** RegularExpression Id. */
  int PRS15 = 22;
  /** RegularExpression Id. */
  int PRS16 = 23;
  /** RegularExpression Id. */
  int PRS17 = 24;
  /** RegularExpression Id. */
  int PRS18 = 25;
  /** RegularExpression Id. */
  int PRS19 = 26;
  /** RegularExpression Id. */
  int PRS20 = 27;
  /** RegularExpression Id. */
  int PRS21 = 28;
  /** RegularExpression Id. */
  int PRS22 = 29;
  /** RegularExpression Id. */
  int PRS23 = 30;
  /** RegularExpression Id. */
  int PRS24 = 31;
  /** RegularExpression Id. */
  int PRS25 = 32;
  /** RegularExpression Id. */
  int PRS26 = 33;
  /** RegularExpression Id. */
  int SRS01 = 34;
  /** RegularExpression Id. */
  int SRS02 = 35;
  /** RegularExpression Id. */
  int SRS03 = 36;
  /** RegularExpression Id. */
  int SRS04 = 37;
  /** RegularExpression Id. */
  int SRS05 = 38;
  /** RegularExpression Id. */
  int SRS06 = 39;
  /** RegularExpression Id. */
  int SRS07 = 40;
  /** RegularExpression Id. */
  int SRS08 = 41;
  /** RegularExpression Id. */
  int SRS09 = 42;
  /** RegularExpression Id. */
  int SRS10 = 43;
  /** RegularExpression Id. */
  int SRS11 = 44;
  /** RegularExpression Id. */
  int SRS12 = 45;
  /** RegularExpression Id. */
  int SRS13 = 46;
  /** RegularExpression Id. */
  int SRS14 = 47;
  /** RegularExpression Id. */
  int SRS15 = 48;
  /** RegularExpression Id. */
  int SRS16 = 49;
  /** RegularExpression Id. */
  int SRS17 = 50;
  /** RegularExpression Id. */
  int SRS18 = 51;
  /** RegularExpression Id. */
  int SRS19 = 52;
  /** RegularExpression Id. */
  int SRS20 = 53;
  /** RegularExpression Id. */
  int SRS21 = 54;
  /** RegularExpression Id. */
  int SRS22 = 55;
  /** RegularExpression Id. */
  int LETRA = 56;
  /** RegularExpression Id. */
  int DIGITO = 57;
  /** RegularExpression Id. */
  int IDENTIFIER = 58;
  /** RegularExpression Id. */
  int INT_CONST = 59;
  /** RegularExpression Id. */
  int REAL_CONST = 60;
  /** RegularExpression Id. */
  int EXPONENT = 61;
  /** RegularExpression Id. */
  int STRING_CONST = 62;
  /** RegularExpression Id. */
  int CHAR_CONST = 63;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<token of kind 6>",
    "<token of kind 7>",
    "\"integer\"",
    "\"real\"",
    "\"character\"",
    "\"string\"",
    "\"boolean\"",
    "\"void\"",
    "\"true\"",
    "\"false\"",
    "\"varType\"",
    "\"funcType\"",
    "\"paramType\"",
    "\"declarations\"",
    "\"endDeclarations\"",
    "\"program\"",
    "\"endProgram\"",
    "\"functions\"",
    "\"endFunctions\"",
    "\"endFunction\"",
    "\"return\"",
    "\"if\"",
    "\"else\"",
    "\"endif\"",
    "\"while\"",
    "\"endWhile\"",
    "\"break\"",
    "\"print\"",
    "\";\"",
    "\",\"",
    "\":\"",
    "\":=\"",
    "\"?\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"==\"",
    "<SRS18>",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "<LETRA>",
    "<DIGITO>",
    "<IDENTIFIER>",
    "<INT_CONST>",
    "<REAL_CONST>",
    "<EXPONENT>",
    "<STRING_CONST>",
    "<CHAR_CONST>",
    "<token of kind 64>",
  };

}
